name       : haskell-open-browser
version    : 0.2.1.0
release    : 4
source     :
    - http://hackage.haskell.org/package/open-browser-0.2.1.0/open-browser-0.2.1.0.tar.gz : 0bed2e63800f738e78a4803ed22902accb50ac02068b96c17ce83a267244ca66
license    : BSD-3-Clause
component  : programming.haskell
summary    : Open a web browser from Haskell.
description: |
    Open a web browser from Haskell.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
    rm -rf $installdir/usr/bin
